# Generated by Django 5.1.7 on 2025-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='STAFF', max_length=10),
        ),
    ]
