# Generated by Django 5.1.7 on 2025-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
