# Generated by Django 5.1.7 on 2025-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_district_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_general_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_push_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_submission_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_weekly_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
