# Generated by Django 5.1.7 on 2025-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_of_report',
            new_name='end_date_of_report',
        ),
        migrations.AddField(
            model_name='report',
            name='start_date_of_report',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
