# Generated by Django 5.1.7 on 2025-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_report_status_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
